spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/forja_do_escritor_db
spring.datasource.username=postgres
# spring.datasource.password=postgres
spring.datasource.password=${DB_PASSWORD}

# --- Configuração do JPA e Hibernate ---

# 'update': O Hibernate tentará atualizar o schema do banco de dados ao iniciar.
# Ótimo para desenvolvimento.
spring.jpa.hibernate.ddl-auto=update

# 'true': Mostra os comandos SQL gerados pelo Hibernate no console.
# Ótimo para debug.
spring.jpa.show-sql=true

# 'false': Boa prática para evitar que transações com o banco fiquem abertas desnecessariamente.
spring.jpa.open-in-view=false